bot:
  build: .
  command: python bot.py
  volumes:
    - .:/code
  links:
    - db
  environment:
    DATABASE_URL: "postgres://postgres@db:5432/postgres"
  env_file:
    - .google.env
    - .twitter.env

db:
  image: postgres
