import os

TMP_DIR = './tmp'
FRAME_FILENAME_FORMAT = os.path.join(TMP_DIR, 'frame-%03d.jpg')
FRAMERATE = 30

AUDIO_FILE = 'assets/audio.mp3'

SECTION_LENGTH_THEN = 2.35
SECTION_LENGTH_NOW = 4.0

MIN_FRAMES_THEN = 1
MAX_FRAMES_THEN = 5
MIN_FRAMES_NOW = 2
MAX_FRAMES_NOW = 4
